name: release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  default:
    name: Application
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build Application
        run: go build -o dist/amqp-proxy cmd/main.go
        env:
          CGO_ENABLED: 0
          GO111MODULE: on
          GOARCH: amd64
          GOOS: linux
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kainonly/amqp-proxy
          tag_with_ref: true